version: '2.1'

services:
  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
